// Copyright (c) 2026 MeetTrace contributors.
// SPDX-License-Identifier: MIT

import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');
  final header = packageRoot.resolve('src/meettrace_whisper.h');
  final bindings = packageRoot.resolve(
    'lib/src/third_party/meettrace_whisper.g.dart',
  );
  final recordUseMapping = packageRoot.resolve(
    'lib/src/third_party/meettrace_whisper.record_use_mapping.g.dart',
  );
  const includedFunctions = {
    'mt_whisper_runtime_version',
    'mt_whisper_abi_version',
    'mt_whisper_config_v1_init',
    'mt_whisper_validate_config_v1',
    'mt_whisper_create_v1',
    'mt_whisper_status_message',
    'mt_whisper_create',
    'mt_whisper_transcribe',
    'mt_whisper_segment_count',
    'mt_whisper_segment_text',
    'mt_whisper_segment_start_ms',
    'mt_whisper_segment_end_ms',
    'mt_whisper_last_error',
    'mt_whisper_cancel',
    'mt_whisper_destroy',
    'mt_whisper_vad_config_v1_init',
    'mt_whisper_vad_validate_config_v1',
    'mt_whisper_vad_create_v1',
    'mt_whisper_vad_segment_samples',
    'mt_whisper_vad_segment_count',
    'mt_whisper_vad_segment_start_sample',
    'mt_whisper_vad_segment_end_sample',
    'mt_whisper_vad_last_error',
    'mt_whisper_vad_reset',
    'mt_whisper_vad_cancel',
    'mt_whisper_vad_destroy',
  };

  final generator = FfiGenerator(
    headers: Headers(entryPoints: [header]),
    functions: Functions(
      include: (declaration) =>
          includedFunctions.contains(declaration.originalName),
      recordUse: (_) => true,
    ),
    structs: Structs(
      include: (declaration) => {
        'mt_whisper_context',
        'mt_whisper_config_v1',
        'mt_whisper_vad_context',
        'mt_whisper_vad_config_v1',
      }.contains(declaration.originalName),
    ),
    typedefs: Typedefs(
      include: (declaration) => {
        'mt_whisper_context',
        'mt_whisper_config_v1',
        'mt_whisper_vad_context',
        'mt_whisper_vad_config_v1',
      }.contains(declaration.originalName),
    ),
    output: Output(
      dartFile: bindings,
      recordUseMapping: recordUseMapping,
      style: const NativeExternalBindings(
        assetId:
            'package:meettrace_whisper_native/src/third_party/'
            'meettrace_whisper.g.dart',
      ),
      format: true,
      preamble: '''
// Copyright (c) 2026 MeetTrace contributors.
// SPDX-License-Identifier: MIT
//
// Generated by package:ffigen. Do not edit manually.
// Source: src/meettrace_whisper.h
// Regenerate: dart run tool/ffigen.dart
//
// ignore_for_file: type=lint, unused_import, unused_element
''',
    ),
  );
  final libclangPath = Platform.environment['LIBCLANG_PATH'];
  generator.generate(
    libclangDylib: libclangPath == null ? null : Uri.file(libclangPath),
  );
}
