part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Color tokens and theme extensions for the generated theme.
final FColors lightColors = FColors(
  brightness: .light,
  systemOverlayStyle: appSystemUiOverlayStyle(.light),
  barrier: Color(0x66111111),
  background: Color(0xFFF7F7F5),
  foreground: Color(0xFF111111),
  primary: Color(0xFF111111),
  primaryForeground: Color(0xFFFAFAF8),
  secondary: Color(0xFFEFEFEC),
  secondaryForeground: Color(0xFF111111),
  muted: Color(0xFFEFEFEC),
  mutedForeground: Color(0xFF52524E),
  destructive: Color(0xFF111111),
  destructiveForeground: Color(0xFFFAFAF8),
  error: Color(0xFF111111),
  errorForeground: Color(0xFFFAFAF8),
  card: Color(0xFFFFFFFF),
  border: Color(0xFFD8D8D3),
  extensions: const [AppColors.light()],
);

final FColors darkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: appSystemUiOverlayStyle(.dark),
  barrier: Color(0xB3000000),
  background: Color(0xFF0D0D0D),
  foreground: Color(0xFFF4F4F1),
  primary: Color(0xFFF4F4F1),
  primaryForeground: Color(0xFF111111),
  secondary: Color(0xFF202020),
  secondaryForeground: Color(0xFFF4F4F1),
  muted: Color(0xFF202020),
  mutedForeground: Color(0xFFB7B7B0),
  destructive: Color(0xFFF4F4F1),
  destructiveForeground: Color(0xFF111111),
  error: Color(0xFFF4F4F1),
  errorForeground: Color(0xFF111111),
  card: Color(0xFF151515),
  border: Color(0xFF343432),
  extensions: const [AppColors.dark()],
);

/// Provides convenient access to theme extensions on [FColors].
///
/// ```dart
/// final accent = context.theme.colors.app.accent; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final accent = context.theme.colors.accent; ✅
///
/// final accent = context.theme.colors.extension<AppColors>().accent; ❌
/// ```
extension FColorsExtensions on FColors {
  AppColors get app => extension<AppColors>();
}

/// Custom color tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
class AppColors extends ThemeExtension<AppColors> {
  const AppColors({
    required this.surfaceRaised,
    required this.inkSecondary,
    required this.recording,
    required this.recordingForeground,
    required this.warning,
    required this.warningForeground,
    required this.success,
    required this.successForeground,
    required this.focusRing,
    required this.borderStrong,
  });

  const AppColors.light()
    : surfaceRaised = const Color(0xFFFFFFFF),
      inkSecondary = const Color(0xFF52524E),
      recording = const Color(0xFF111111),
      recordingForeground = const Color(0xFFFAFAF8),
      warning = const Color(0xFF3F3F3C),
      warningForeground = const Color(0xFFFAFAF8),
      success = const Color(0xFF111111),
      successForeground = const Color(0xFFFAFAF8),
      focusRing = const Color(0xFF111111),
      borderStrong = const Color(0xFF8B8B85);

  const AppColors.dark()
    : surfaceRaised = const Color(0xFF151515),
      inkSecondary = const Color(0xFFB7B7B0),
      recording = const Color(0xFFF4F4F1),
      recordingForeground = const Color(0xFF111111),
      warning = const Color(0xFFB7B7B0),
      warningForeground = const Color(0xFF111111),
      success = const Color(0xFFF4F4F1),
      successForeground = const Color(0xFF111111),
      focusRing = const Color(0xFFF4F4F1),
      borderStrong = const Color(0xFF777772);

  final Color surfaceRaised;
  final Color inkSecondary;
  final Color recording;
  final Color recordingForeground;
  final Color warning;
  final Color warningForeground;
  final Color success;
  final Color successForeground;
  final Color focusRing;
  final Color borderStrong;

  @override
  AppColors copyWith({
    Color? surfaceRaised,
    Color? inkSecondary,
    Color? recording,
    Color? recordingForeground,
    Color? warning,
    Color? warningForeground,
    Color? success,
    Color? successForeground,
    Color? focusRing,
    Color? borderStrong,
  }) => AppColors(
    surfaceRaised: surfaceRaised ?? this.surfaceRaised,
    inkSecondary: inkSecondary ?? this.inkSecondary,
    recording: recording ?? this.recording,
    recordingForeground: recordingForeground ?? this.recordingForeground,
    warning: warning ?? this.warning,
    warningForeground: warningForeground ?? this.warningForeground,
    success: success ?? this.success,
    successForeground: successForeground ?? this.successForeground,
    focusRing: focusRing ?? this.focusRing,
    borderStrong: borderStrong ?? this.borderStrong,
  );

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other == null) {
      return this;
    }
    return AppColors(
      surfaceRaised: Color.lerp(surfaceRaised, other.surfaceRaised, t)!,
      inkSecondary: Color.lerp(inkSecondary, other.inkSecondary, t)!,
      recording: Color.lerp(recording, other.recording, t)!,
      recordingForeground: Color.lerp(
        recordingForeground,
        other.recordingForeground,
        t,
      )!,
      warning: Color.lerp(warning, other.warning, t)!,
      warningForeground: Color.lerp(
        warningForeground,
        other.warningForeground,
        t,
      )!,
      success: Color.lerp(success, other.success, t)!,
      successForeground: Color.lerp(
        successForeground,
        other.successForeground,
        t,
      )!,
      focusRing: Color.lerp(focusRing, other.focusRing, t)!,
      borderStrong: Color.lerp(borderStrong, other.borderStrong, t)!,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppColors &&
          runtimeType == other.runtimeType &&
          surfaceRaised == other.surfaceRaised &&
          inkSecondary == other.inkSecondary &&
          recording == other.recording &&
          recordingForeground == other.recordingForeground &&
          warning == other.warning &&
          warningForeground == other.warningForeground &&
          success == other.success &&
          successForeground == other.successForeground &&
          focusRing == other.focusRing &&
          borderStrong == other.borderStrong;

  @override
  int get hashCode => Object.hash(
    runtimeType,
    surfaceRaised,
    inkSecondary,
    recording,
    recordingForeground,
    warning,
    warningForeground,
    success,
    successForeground,
    focusRing,
    borderStrong,
  );
}
