part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Icon tokens for the generated theme.
FIcons _icons() => FIcons(
  arrowLeft: const FIcon(FLucideIcons.arrowLeft),
  calendar: const FIcon(FLucideIcons.calendar),
  check: const FIcon(FLucideIcons.check),
  chevronDown: const FIcon(FLucideIcons.chevronDown),
  chevronLeft: const FIcon(FLucideIcons.chevronLeft),
  chevronRight: const FIcon(FLucideIcons.chevronRight),
  chevronUp: const FIcon(FLucideIcons.chevronUp),
  chevronsUpDown: const FIcon(FLucideIcons.chevronsUpDown),
  circleAlert: const FIcon(FLucideIcons.circleAlert),
  clock4: const FIcon(FLucideIcons.clock4),
  ellipsis: const FIcon(FLucideIcons.ellipsis),
  error: const FIcon(FLucideIcons.circleAlert),
  eye: const FIcon(FLucideIcons.eye),
  eyeClosed: const FIcon(FLucideIcons.eyeClosed),
  gripHorizontal: const FIcon(FLucideIcons.gripHorizontal),
  gripVertical: const FIcon(FLucideIcons.gripVertical),
  loader: const FIcon(FLucideIcons.loader),
  loaderCircle: const FIcon(FLucideIcons.loaderCircle),
  loaderPinwheel: const FIcon(FLucideIcons.loaderPinwheel),
  search: const FIcon(FLucideIcons.search),
  userRound: const FIcon(FLucideIcons.userRound),
  x: const FIcon(FLucideIcons.x),
);
