part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Icon tokens for the generated theme.
FIcons _icons() => FIcons(
  arrowLeft: FIcons.iconData(FLucideIcons.arrowLeft),
  calendar: FIcons.iconData(FLucideIcons.calendar),
  check: FIcons.iconData(FLucideIcons.check),
  chevronDown: FIcons.iconData(FLucideIcons.chevronDown),
  chevronLeft: FIcons.iconData(FLucideIcons.chevronLeft),
  chevronRight: FIcons.iconData(FLucideIcons.chevronRight),
  chevronUp: FIcons.iconData(FLucideIcons.chevronUp),
  chevronsUpDown: FIcons.iconData(FLucideIcons.chevronsUpDown),
  circleAlert: FIcons.iconData(FLucideIcons.circleAlert),
  clock4: FIcons.iconData(FLucideIcons.clock4),
  ellipsis: FIcons.iconData(FLucideIcons.ellipsis),
  error: FIcons.iconData(FLucideIcons.circleAlert),
  eye: FIcons.iconData(FLucideIcons.eye),
  eyeClosed: FIcons.iconData(FLucideIcons.eyeClosed),
  gripHorizontal: FIcons.iconData(FLucideIcons.gripHorizontal),
  gripVertical: FIcons.iconData(FLucideIcons.gripVertical),
  loader: FIcons.iconData(FLucideIcons.loader),
  loaderCircle: FIcons.iconData(FLucideIcons.loaderCircle),
  loaderPinwheel: FIcons.iconData(FLucideIcons.loaderPinwheel),
  search: FIcons.iconData(FLucideIcons.search),
  userRound: FIcons.iconData(FLucideIcons.userRound),
  x: FIcons.iconData(FLucideIcons.x),
);
