part of 'theme.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Style tokens and theme extensions for the generated theme.
FStyle _style({
  required FColors colors,
  required FTypography typography,
  required bool touch,
}) {
  const borderRadius = FBorderRadius();
  return FStyle(
    formFieldStyle: .inherit(
      colors: colors,
      typography: typography,
      touch: touch,
    ),
    focusedOutlineStyle: FFocusedOutlineStyle(
      color: colors.primary,
      borderRadius: borderRadius.md,
    ),
    sizes: FSizes.inherit(touch: touch),
    iconStyle: IconThemeData(
      color: colors.foreground,
      size: typography.body.lg.fontSize,
    ),
    tappableStyle: FTappableStyle(),
    borderRadius: const FBorderRadius(),
    borderWidth: 1,
    pagePadding: const .symmetric(vertical: 8, horizontal: 12),
    shadow: const [
      BoxShadow(color: Color(0x0d000000), offset: Offset(0, 1), blurRadius: 2),
    ],
    extensions: const [AppStyle()],
  );
}

/// Provides convenient access to theme extensions on [FStyle].
///
/// ```dart
/// final cardRadius = context.theme.style.app.cardRadius; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final cardRadius = context.theme.style.cardRadius; ✅
///
/// final cardRadius = context.theme.style.extension<AppStyle>().cardRadius; ❌
/// ```
extension FStyleExtensions on FStyle {
  AppStyle get app => extension<AppStyle>();
}

/// Custom style tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
class AppStyle extends ThemeExtension<AppStyle> {
  const AppStyle({
    this.spaceSm = 8,
    this.spaceMd = 16,
    this.spaceLg = 24,
    this.contentMaxWidth = 420,
    this.wideContentMaxWidth = 960,
    this.wideLayoutMinWidth = 720,
    this.emptyIconSize = 48,
  });

  final double spaceSm;
  final double spaceMd;
  final double spaceLg;
  final double contentMaxWidth;
  final double wideContentMaxWidth;
  final double wideLayoutMinWidth;
  final double emptyIconSize;

  @override
  AppStyle copyWith({
    double? spaceSm,
    double? spaceMd,
    double? spaceLg,
    double? contentMaxWidth,
    double? wideContentMaxWidth,
    double? wideLayoutMinWidth,
    double? emptyIconSize,
  }) => AppStyle(
    spaceSm: spaceSm ?? this.spaceSm,
    spaceMd: spaceMd ?? this.spaceMd,
    spaceLg: spaceLg ?? this.spaceLg,
    contentMaxWidth: contentMaxWidth ?? this.contentMaxWidth,
    wideContentMaxWidth: wideContentMaxWidth ?? this.wideContentMaxWidth,
    wideLayoutMinWidth: wideLayoutMinWidth ?? this.wideLayoutMinWidth,
    emptyIconSize: emptyIconSize ?? this.emptyIconSize,
  );

  @override
  AppStyle lerp(covariant AppStyle? other, double t) {
    if (other == null) {
      return this;
    }
    return AppStyle(
      spaceSm: spaceSm + (other.spaceSm - spaceSm) * t,
      spaceMd: spaceMd + (other.spaceMd - spaceMd) * t,
      spaceLg: spaceLg + (other.spaceLg - spaceLg) * t,
      contentMaxWidth:
          contentMaxWidth + (other.contentMaxWidth - contentMaxWidth) * t,
      wideContentMaxWidth:
          wideContentMaxWidth +
          (other.wideContentMaxWidth - wideContentMaxWidth) * t,
      wideLayoutMinWidth:
          wideLayoutMinWidth +
          (other.wideLayoutMinWidth - wideLayoutMinWidth) * t,
      emptyIconSize: emptyIconSize + (other.emptyIconSize - emptyIconSize) * t,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStyle &&
          runtimeType == other.runtimeType &&
          spaceSm == other.spaceSm &&
          spaceMd == other.spaceMd &&
          spaceLg == other.spaceLg &&
          contentMaxWidth == other.contentMaxWidth &&
          wideContentMaxWidth == other.wideContentMaxWidth &&
          wideLayoutMinWidth == other.wideLayoutMinWidth &&
          emptyIconSize == other.emptyIconSize;

  @override
  int get hashCode => Object.hash(
    runtimeType,
    spaceSm,
    spaceMd,
    spaceLg,
    contentMaxWidth,
    wideContentMaxWidth,
    wideLayoutMinWidth,
    emptyIconSize,
  );
}
